branches:
  - master
  - name: '!(master)*'
    prerelease: true
repositoryUrl: git@github.com:mattrcole/env-verify.git
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - "@semantic-release/git"
