name: Pull Request Testing
on:
  push:
    branches:
      - github-workflows

jobs:
  build:
    name: Test and Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test
